CREATE TABLE IF NOT EXISTS jukebox_songs(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    createdate TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    url TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    path TEXT NOT NULL,
    plays INTEGER NOT NULL DEFAULT 0
);
