CREATE TABLE IF NOT EXISTS qdb(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    createdate TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    author TEXT NOT NULL,
    content TEXT NOT NULL,
    deleted INTEGER NOT NULL DEFAULT 0,
    upvotes INTEGER NOT NULL DEFAULT 0,
    downvotes INTEGER NOT NULL DEFAULT 0
);
