CREATE TABLE IF NOT EXISTS user_casebucks(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    createdate TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lastupdated TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user TEXT NOT NULL UNIQUE,
    balance INTEGER NOT NULL DEFAULT 0
);
